/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardShadow: typeof import('./src/components/CardShadow.vue')['default']
    Column: typeof import('./src/components/Column.vue')['default']
    FPSCounter: typeof import('./src/components/FPSCounter.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
